name = "GaussianStates"
uuid = "87be6f6c-69b0-4e4f-9c30-808c15aab153"
authors = ["Davide Ferracin <davide.ferracin@protonmail.com>"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
